# i3 config file for launching applications on startup

set $ans exec_always --no-startup-id
set $ns  exec	     --no-startup-id

# Exec_always
$ans autorandr -c
$ans hsetroot -solid '#1B1F3B'

# Exec
$ns /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
$ns /usr/lib/geoclue-2.0/demos/agent
$ns redshift -t 6500:2500
$ns picom --experimental-backend --backend glx --blur-background --blur-method dual_kawase --blur-strength 8
#$ns clight
