
## Borders
for_window [class=".*"] border pixel 2
gaps outer 0
gaps inner 10
#border_radius 2

## Font
font pango:Terminus (TTF) Bold 14

## Colors
set $x	#FF0000
set $urgent #FF8000
set $focus	#7555FF
set $ufocus	#1B1F3B

client.focused			$x $x $x $focus  $focus
client.focused_inactive	$x $x $x $ufocus $ufocus
client.unfocused		$x $x $x $ufocus $ufocus
client.urgent			$x $x $x $urgent $urgent
